#!/usr/bin/env bundle exec ruby
# This script can only be run from elsewhere if BUNDLE_GEMFILE of this project
# has been set.

require "tsp_playground"
TspPlayground::Shell.run(ARGV, out: $stdout, err: $stderr) do |options|
  TspPlayground::DoSomething.new(options, out: $stdout, err: $stderr).show
end
